"""ood_methods_extended.py

Extended OOD baselines + proposed head-gradient matrix-aware methods.

This module follows the same high-level pattern used in `ood_methods.py`:
    - A base `OODMethod` with `compute_ood_scores(loader)`
    - Some methods also implement `fit(id_loader)`

Supported (implemented) methods:
    - MSP, EnergyBased, Odin (as in the original file)
    - FeatureKNN (kNN distance in penultimate features)
    - FeatureMahalanobis (class-conditional Mahalanobis in penultimate features)
    - GradNorm (gradient-norm OOD score on head weights)
    - GradOrth (feature-subspace orthogonality score; simplified faithful variant)
    - LowDimGradResidual (PCA residual on vec(head-gradient))
    - GradVecMahalanobis (gradient embedding + class-conditional Mahalanobis; refactor of original)
    - TwoSidedHeadGradResidual (PROPOSED: two-sided projection residual on head-gradient)
    - TwoSidedHeadGradCodeMahalanobis (PROPOSED: code embedding + Mahalanobis)

Notes:
    - All gradient-based methods here operate on the *head* (final Linear layer).
    - Loaders are assumed to yield (inputs, labels) tuples; labels are optional for scoring.
    - For robustness and comparability, most gradient-based methods expose a `loss_type`.

Author: generated by ChatGPT.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple, Union

import numpy as np
import torch
import torch.nn.functional as F

from sklearn.decomposition import PCA, IncrementalPCA
from sklearn.neighbors import NearestNeighbors
from sklearn.mixture import GaussianMixture


Batch = Union[Tuple[torch.Tensor, torch.Tensor], torch.Tensor]


def _to_device(x: torch.Tensor, device: torch.device) -> torch.Tensor:
    return x.to(device, non_blocking=True) if torch.is_tensor(x) else x


def _iter_inputs(loader: Iterable[Batch]):
    """Yield (inputs, labels_or_None) from a dataloader that may yield inputs only."""
    for batch in loader:
        if isinstance(batch, (list, tuple)) and len(batch) == 2:
            yield batch[0], batch[1]
        else:
            yield batch, None


def _find_last_linear(model: torch.nn.Module) -> Tuple[str, torch.nn.Linear]:
    """Find the last torch.nn.Linear module in the model."""
    last_name, last_mod = None, None
    for name, m in model.named_modules():
        if isinstance(m, torch.nn.Linear):
            last_name, last_mod = name, m
    if last_mod is None:
        raise RuntimeError("Could not find a torch.nn.Linear head in the model.")
    return last_name, last_mod


@dataclass
class HeadIO:
    h: torch.Tensor  # penultimate features input to head: (B, d)
    logits: torch.Tensor  # head output logits: (B, K)


class HeadExtractor:
    """Utility to capture penultimate features (input to last Linear) and logits."""

    def __init__(self, model: torch.nn.Module):
        self.model = model
        self.head_name, self.head = _find_last_linear(model)

    def forward(self, x: torch.Tensor) -> HeadIO:
        device = next(self.model.parameters()).device
        x = _to_device(x, device)

        captured: Dict[str, torch.Tensor] = {}

        def pre_hook(_module, inputs):
            # inputs is a tuple; for Linear it's (h,)
            captured["h"] = inputs[0]

        handle = self.head.register_forward_pre_hook(pre_hook)
        try:
            logits = self.model(x)
        finally:
            handle.remove()

        if "h" not in captured:
            raise RuntimeError("Failed to capture penultimate features (head input).")
        h = captured["h"]
        # Ensure 2D (B,d)
        if h.dim() > 2:
            h = h.view(h.size(0), -1)
        return HeadIO(h=h, logits=logits)


def _loss_from_logits(
    logits: torch.Tensor,
    loss_type: str = "uniform_kl",
    temperature: float = 1.0,
) -> torch.Tensor:
    """Return per-sample loss L(x) given logits.

    Supported loss_type:
        - 'uniform_kl': KL(p || U) (proxy via cross-entropy to uniform)
        - 'entropy': negative entropy (encourage high entropy)
        - 'anti_top1': penalize the predicted top-1 probability
        - 'margin': softplus(z2 - z1) using top-1/top-2 logits
        - 'ce_pred': cross-entropy with predicted class (self-target)
    """
    if temperature <= 0:
        raise ValueError("temperature must be > 0")
    z = logits / temperature
    p = torch.softmax(z, dim=1)
    K = p.size(1)

    if loss_type == "uniform_kl":
        # KL(p || U) = sum p log p - sum p log(1/K) = sum p log p + log K
        # up to constant, minimize negative entropy; for gradient signal, use KL explicitly:
        # KL(p||U) = sum p * (log p - log(1/K))
        # We'll compute directly (stable):
        logp = torch.log(p.clamp_min(1e-12))
        loss = (p * (logp + np.log(K))).sum(dim=1)
        return loss

    if loss_type == "entropy":
        # Negative entropy (lower entropy => larger loss)
        logp = torch.log(p.clamp_min(1e-12))
        ent = -(p * logp).sum(dim=1)
        return -ent

    if loss_type == "anti_top1":
        top1 = p.max(dim=1).values
        # -log(1 - top1) (clamped)
        return -torch.log((1.0 - top1).clamp(1e-6, 1.0))

    if loss_type == "margin":
        top2 = torch.topk(z, k=2, dim=1).values
        z1 = top2[:, 0]
        z2 = top2[:, 1]
        return F.softplus(z2 - z1)

    if loss_type == "ce_pred":
        yhat = torch.argmax(z, dim=1)
        return F.cross_entropy(z, yhat, reduction="none")

    raise ValueError(f"Unknown loss_type: {loss_type}")


def _head_grad_matrix(
    head_io: HeadIO,
    loss_type: str = "uniform_kl",
    temperature: float = 1.0,
) -> torch.Tensor:
    """Compute per-sample head gradient matrix G = dL/dW as (B, K, d).

    Uses autograd to compute delta = dL/dlogits, then G = delta ⊗ h.
    """
    logits = head_io.logits
    h = head_io.h
    # Ensure logits require grad
    if not logits.requires_grad:
        logits = logits.detach().requires_grad_(True)

    loss = _loss_from_logits(logits, loss_type=loss_type, temperature=temperature)
    # Sum to get scalar for autograd; then reshape back using grad_output ones
    # We want per-sample delta; easiest: compute gradient of loss.sum() w.r.t logits.
    delta = torch.autograd.grad(loss.sum(), logits, retain_graph=False, create_graph=False)[0]
    # G[b] = delta[b][:,None] * h[b][None,:]
    G = delta.unsqueeze(2) * h.unsqueeze(1)
    return G


class OODMethod:
    def __init__(self, model: torch.nn.Module):
        self.model = model
        self.model.eval()

    def fit(self, loader: Iterable[Batch]):
        """Optional: fit statistics on in-distribution data."""
        return

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        raise NotImplementedError


# ----------------------------
# Simple logit-based baselines
# ----------------------------

class MSP(OODMethod):
    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                logits = self.model(x)
                p = torch.softmax(logits, dim=1)
                scores.append(1.0 - p.max(dim=1).values.detach().cpu())
        return torch.cat(scores, dim=0)


class EnergyBased(OODMethod):
    def __init__(self, model: torch.nn.Module, temperature: float = 1.0):
        super().__init__(model)
        self.temperature = temperature

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                logits = self.model(x) / self.temperature
                energy = -torch.logsumexp(logits, dim=1)
                scores.append(energy.detach().cpu())
        return torch.cat(scores, dim=0)


class Odin(OODMethod):
    def __init__(self, model: torch.nn.Module, epsilon: float = 0.001, temperature: float = 1.0):
        super().__init__(model)
        self.epsilon = epsilon
        self.temperature = temperature

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            x = x.detach().requires_grad_(True)
            logits = self.model(x) / self.temperature
            # maximize max logit -> minimize negative
            loss = -logits.max(dim=1).values.mean()
            self.model.zero_grad(set_to_none=True)
            if x.grad is not None:
                x.grad.zero_()
            loss.backward()
            x_pert = (x + self.epsilon * x.grad.sign()).detach()
            with torch.no_grad():
                logits_p = self.model(x_pert) / self.temperature
                p = torch.softmax(logits_p, dim=1)
                scores.append((1.0 - p.max(dim=1).values).cpu())
        return torch.cat(scores, dim=0)


# ----------------------------
# Feature-based baselines
# ----------------------------

class FeatureKNN(OODMethod):
    """kNN distance in penultimate feature space."""

    def __init__(self, model: torch.nn.Module, k: int = 10, metric: str = "euclidean"):
        super().__init__(model)
        self.k = k
        self.metric = metric
        self.extractor = HeadExtractor(self.model)
        self.nn: Optional[NearestNeighbors] = None

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        feats: List[np.ndarray] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                h = self.extractor.forward(x).h
                feats.append(h.detach().cpu().numpy())
        X = np.concatenate(feats, axis=0)
        self.nn = NearestNeighbors(n_neighbors=self.k, metric=self.metric, n_jobs=1)
        self.nn.fit(X)

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if self.nn is None:
            raise RuntimeError("FeatureKNN.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                h = self.extractor.forward(x).h.detach().cpu().numpy()
                dists, _ = self.nn.kneighbors(h, n_neighbors=self.k)
                # Use mean kNN distance as OOD score
                scores.append(torch.from_numpy(dists.mean(axis=1)))
        return torch.cat(scores, dim=0)


class FeatureMahalanobis(OODMethod):
    """Class-conditional Gaussian in penultimate feature space; score=min Mahalanobis."""

    def __init__(self, model: torch.nn.Module, shrinkage: float = 1e-6):
        super().__init__(model)
        self.extractor = HeadExtractor(self.model)
        self.shrinkage = shrinkage
        self.class_stats: Dict[int, Tuple[np.ndarray, np.ndarray]] = {}

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        feats: List[np.ndarray] = []
        labels: List[int] = []
        with torch.no_grad():
            for x, y in _iter_inputs(loader):
                if y is None:
                    raise RuntimeError("FeatureMahalanobis.fit requires labels.")
                x = _to_device(x, device)
                h = self.extractor.forward(x).h.detach().cpu().numpy()
                feats.append(h)
                labels.extend(y.detach().cpu().reshape(-1).tolist())
        X = np.concatenate(feats, axis=0)
        y = np.array(labels)
        self.class_stats = {}
        for c in np.unique(y):
            Xc = X[y == c]
            mu = Xc.mean(axis=0)
            cov = np.cov(Xc, rowvar=False)
            cov = cov + self.shrinkage * np.eye(cov.shape[0])
            self.class_stats[int(c)] = (mu, np.linalg.inv(cov))

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if not self.class_stats:
            raise RuntimeError("FeatureMahalanobis.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                h = self.extractor.forward(x).h.detach().cpu().numpy()
                batch_scores = []
                for i in range(h.shape[0]):
                    xi = h[i]
                    best = np.inf
                    for mu, inv_cov in self.class_stats.values():
                        d = xi - mu
                        md = float(np.sqrt(d.T @ inv_cov @ d))
                        best = min(best, md)
                    batch_scores.append(best)
                scores.append(torch.tensor(batch_scores))
        return torch.cat(scores, dim=0)


class FeaturePCA(OODMethod):
    """OpenPCS style: PCA on penultimate features, score = reconstruction error."""
    
    def __init__(self, model: torch.nn.Module, n_components: float = 0.95):
        super().__init__(model)
        self.extractor = HeadExtractor(self.model)
        self.n_components = n_components
        self.pca: Optional[PCA] = None

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        feats: List[np.ndarray] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                h = self.extractor.forward(x).h.detach().cpu().numpy()
                feats.append(h)
        X = np.concatenate(feats, axis=0)
        n_comp = int(self.n_components) if self.n_components > 1 else self.n_components
        self.pca = PCA(n_components=n_comp)
        self.pca.fit(X)

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if self.pca is None:
            raise RuntimeError("FeaturePCA.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                h = self.extractor.forward(x).h.detach().cpu().numpy()
                h_proj = self.pca.transform(h)
                h_rec = self.pca.inverse_transform(h_proj)
                # Reconstruction error: higher means OOD.
                resid = np.linalg.norm(h - h_rec, axis=1)
                scores.append(torch.from_numpy(resid))
        return torch.cat(scores, dim=0)


class FeatureGMM(OODMethod):
    """Class-conditional GMM (Gaussian Mixture Model) in penultimate feature space."""
    
    def __init__(self, model: torch.nn.Module, n_components: int = 2, covariance_type: str = 'full'):
        super().__init__(model)
        self.extractor = HeadExtractor(self.model)
        self.n_components = n_components
        self.covariance_type = covariance_type
        self.class_gmms: Dict[int, GaussianMixture] = {}

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        feats: List[np.ndarray] = []
        labels: List[int] = []
        with torch.no_grad():
            for x, y in _iter_inputs(loader):
                if y is None:
                    raise RuntimeError("FeatureGMM.fit requires labels.")
                x = _to_device(x, device)
                h = self.extractor.forward(x).h.detach().cpu().numpy()
                feats.append(h)
                labels.extend(y.detach().cpu().reshape(-1).tolist())
        X = np.concatenate(feats, axis=0)
        y = np.array(labels)
        self.class_gmms = {}
        for c in np.unique(y):
            Xc = X[y == c]
            gmm = GaussianMixture(n_components=self.n_components, covariance_type=self.covariance_type, reg_covar=1e-5)
            gmm.fit(Xc)
            self.class_gmms[int(c)] = gmm

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if not self.class_gmms:
            raise RuntimeError("FeatureGMM.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                h = self.extractor.forward(x).h.detach().cpu().numpy()
                batch_scores = []
                for i in range(h.shape[0]):
                    xi = h[i:i+1] # keep 2d shape (1, D)
                    best_nll = np.inf
                    for gmm in self.class_gmms.values():
                        # score_samples gives log likelihoods, so negative log likelihood is an OOD metric (higher=OOD)
                        ll = gmm.score_samples(xi)[0]
                        nll = -ll
                        best_nll = min(best_nll, nll)
                    batch_scores.append(best_nll)
                scores.append(torch.tensor(batch_scores))
        return torch.cat(scores, dim=0)


# ----------------------------
# Gradient-based baselines
# ----------------------------

class GradNorm(OODMethod):
    """Gradient norm score on head weights for a chosen loss/target."""

    def __init__(self, model: torch.nn.Module, loss_type: str = "uniform_kl", p: str = "fro", temperature: float = 1.0):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.p = p  # 'fro' or 'l1'
        self.extractor = HeadExtractor(self.model)

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            self.model.zero_grad(set_to_none=True)
            head_io = self.extractor.forward(x)
            # We need gradients; do not use no_grad.
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)  # (B,K,d)
            if self.p == "fro":
                s = torch.linalg.vector_norm(G.flatten(1), ord=2, dim=1)
            elif self.p == "l1":
                s = G.abs().flatten(1).sum(dim=1)
            else:
                raise ValueError("p must be 'fro' or 'l1'")
            scores.append(s.detach().cpu())
        return torch.cat(scores, dim=0)


class GradOrth(OODMethod):
    """Simplified GradOrth-style score.

    Fit: build feature subspace from penultimate features h (ID) via SVD/PCA.
    Score: gradient component orthogonal to feature subspace.

    For head-gradient G = delta h^T, the feature-orthogonal gradient is delta h_perp^T.
    Score = ||delta h_perp^T||_F = ||delta|| * ||h_perp||.
    """

    def __init__(
        self,
        model: torch.nn.Module,
        eps_th: float = 0.95,
        loss_type: str = "uniform_kl",
        temperature: float = 1.0,
        center: bool = True,
    ):
        super().__init__(model)
        self.eps_th = eps_th
        self.loss_type = loss_type
        self.temperature = temperature
        self.center = center
        self.extractor = HeadExtractor(self.model)
        self.U: Optional[torch.Tensor] = None  # (d,k)
        self.mu: Optional[torch.Tensor] = None

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        feats: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                feats.append(self.extractor.forward(x).h.detach())
        H = torch.cat(feats, dim=0)  # (N,d)
        if self.center:
            self.mu = H.mean(dim=0, keepdim=True)
            Hc = H - self.mu
        else:
            self.mu = torch.zeros(1, H.size(1), device=H.device)
            Hc = H
        # Compute SVD of (d x N) matrix as in GradOrth (R = [h1,...,hN])
        R = Hc.T  # (d,N)
        # torch.linalg.svd returns U(d,d), S(min), Vh(N,N)
        U, S, _ = torch.linalg.svd(R, full_matrices=False)
        energy = (S ** 2)
        cum = torch.cumsum(energy, dim=0) / energy.sum()
        k = int(torch.searchsorted(cum, torch.tensor(self.eps_th, device=cum.device)).item() + 1)
        k = max(1, min(k, U.size(1)))
        self.U = U[:, :k].detach()  # (d,k)

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if self.U is None or self.mu is None:
            raise RuntimeError("GradOrth.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        U = self.U.to(device)
        mu = self.mu.to(device)
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            # compute delta and h
            logits = head_io.logits.detach().requires_grad_(True)
            h = head_io.h
            if self.center:
                h = h - mu
            loss = _loss_from_logits(logits, loss_type=self.loss_type, temperature=self.temperature)
            delta = torch.autograd.grad(loss.sum(), logits, retain_graph=False, create_graph=False)[0]
            # h_perp = h - UU^T h
            proj = (h @ U) @ U.T
            h_perp = h - proj
            # Score = ||delta|| * ||h_perp||
            s = torch.linalg.vector_norm(delta, ord=2, dim=1) * torch.linalg.vector_norm(h_perp, ord=2, dim=1)
            scores.append(s.detach().cpu())
        return torch.cat(scores, dim=0)


class LowDimGradResidual(OODMethod):
    """PCA on vec(head-gradient) using ID, then use reconstruction residual norm as score."""

    def __init__(
        self,
        model: torch.nn.Module,
        loss_type: str = "uniform_kl",
        temperature: float = 1.0,
        n_components: float = 0.95,
        max_components: int = 256,
        pca_batch_size: int = 512,
    ):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.n_components = n_components
        self.max_components = max_components
        self.pca_batch_size = pca_batch_size
        self.extractor = HeadExtractor(self.model)
        self.pca: Optional[PCA] = None
        self.mean_: Optional[np.ndarray] = None

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        total = 0
        sum_vec: Optional[np.ndarray] = None
        n_features = None
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)
            v = G.flatten(1).detach().cpu().numpy()
            if sum_vec is None:
                n_features = v.shape[1]
                sum_vec = v.sum(axis=0, dtype=np.float64)
            else:
                sum_vec += v.sum(axis=0, dtype=np.float64)
            total += v.shape[0]
        if sum_vec is None or n_features is None or total == 0:
            raise RuntimeError("LowDimGradResidual.fit received no samples.")
        self.mean_ = (sum_vec / total).astype(np.float32, copy=False)[None, :]

        max_k = min(total, n_features)
        if isinstance(self.n_components, float):
            n_comp = max(1, int(max_k * self.n_components))
        else:
            n_comp = int(self.n_components)
        n_comp = max(1, min(max_k, self.max_components, n_comp))

        self.pca = IncrementalPCA(n_components=n_comp, batch_size=self.pca_batch_size)
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)
            v = G.flatten(1).detach().cpu().numpy()
            Xc = v - self.mean_
            self.pca.partial_fit(Xc)

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if self.pca is None or self.mean_ is None:
            raise RuntimeError("LowDimGradResidual.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)
            X = G.flatten(1).detach().cpu().numpy()
            Xc = X - self.mean_
            Z = self.pca.transform(Xc)
            Xrec = self.pca.inverse_transform(Z)
            resid = np.linalg.norm(Xc - Xrec, axis=1)
            scores.append(torch.from_numpy(resid))
        return torch.cat(scores, dim=0)


class GradVecMahalanobis(OODMethod):
    """GradVec-like baseline: use per-sample vec(head-gradient) -> PCA -> class-conditional Mahalanobis."""

    def __init__(
        self,
        model: torch.nn.Module,
        loss_type: str = "uniform_kl",
        temperature: float = 1.0,
        n_components: float = 0.95,
        shrinkage: float = 1e-6,
        max_components: int = 256,
        pca_batch_size: int = 512,
    ):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.n_components = n_components
        self.shrinkage = shrinkage
        self.max_components = max_components
        self.pca_batch_size = pca_batch_size
        self.extractor = HeadExtractor(self.model)
        self.pca: Optional[PCA] = None
        self.mean_: Optional[np.ndarray] = None
        self.class_stats: Dict[int, Tuple[np.ndarray, np.ndarray]] = {}

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        total = 0
        sum_vec: Optional[np.ndarray] = None
        n_features = None
        for x, y in _iter_inputs(loader):
            if y is None:
                raise RuntimeError("GradVecMahalanobis.fit requires labels.")
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)
            v = G.flatten(1).detach().cpu().numpy()
            if sum_vec is None:
                n_features = v.shape[1]
                sum_vec = v.sum(axis=0, dtype=np.float64)
            else:
                sum_vec += v.sum(axis=0, dtype=np.float64)
            total += v.shape[0]
        if sum_vec is None or n_features is None or total == 0:
            raise RuntimeError("GradVecMahalanobis.fit received no samples.")
        self.mean_ = (sum_vec / total).astype(np.float32, copy=False)[None, :]

        max_k = min(total, n_features)
        if isinstance(self.n_components, float):
            n_comp = max(1, int(max_k * self.n_components))
        else:
            n_comp = int(self.n_components)
        n_comp = max(1, min(max_k, self.max_components, n_comp))

        self.pca = IncrementalPCA(n_components=n_comp, batch_size=self.pca_batch_size)
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)
            v = G.flatten(1).detach().cpu().numpy()
            Xc = v - self.mean_
            self.pca.partial_fit(Xc)

        labels: List[int] = []
        Xr_chunks: List[np.ndarray] = []
        for x, y in _iter_inputs(loader):
            if y is None:
                raise RuntimeError("GradVecMahalanobis.fit requires labels.")
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)
            v = G.flatten(1).detach().cpu().numpy()
            Xc = v - self.mean_
            Xr_chunks.append(self.pca.transform(Xc))
            labels.extend(y.detach().cpu().reshape(-1).tolist())
        Xr = np.concatenate(Xr_chunks, axis=0)
        y = np.array(labels)
        self.class_stats = {}
        for c in np.unique(y):
            Xc_c = Xr[y == c]
            mu = Xc_c.mean(axis=0)
            cov = np.cov(Xc_c, rowvar=False) + self.shrinkage * np.eye(Xc_c.shape[1])
            self.class_stats[int(c)] = (mu, np.linalg.inv(cov))

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if self.pca is None or self.mean_ is None or not self.class_stats:
            raise RuntimeError("GradVecMahalanobis.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            G = _head_grad_matrix(head_io, loss_type=self.loss_type, temperature=self.temperature)
            X = G.flatten(1).detach().cpu().numpy()
            Xc = X - self.mean_
            Z = self.pca.transform(Xc)
            batch_scores = []
            for i in range(Z.shape[0]):
                zi = Z[i]
                best = np.inf
                for mu, inv_cov in self.class_stats.values():
                    d = zi - mu
                    md = float(np.sqrt(d.T @ inv_cov @ d))
                    best = min(best, md)
                batch_scores.append(best)
            scores.append(torch.tensor(batch_scores))
        return torch.cat(scores, dim=0)


# ----------------------------
# Proposed methods (head matrix-aware)
# ----------------------------

class TwoSidedHeadGradResidual(OODMethod):
    """PROPOSED: learn U (classes) and V (features) and score by two-sided residual.

    We learn:
        U from covariance of delta (dL/dlogits) over ID
        V from covariance of h (penultimate features) over ID

    Then score (per-sample):
        r = ||G_hat - U U^T G_hat V V^T||_F
    with G_hat = G / (||G||_F + eps)
    """

    def __init__(
        self,
        model: torch.nn.Module,
        loss_type: str = "uniform_kl",
        temperature: float = 1.0,
        eps_th_u: float = 0.95,
        eps_th_v: float = 0.95,
        eps: float = 1e-12,
        center_h: bool = True,
    ):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.eps_th_u = eps_th_u
        self.eps_th_v = eps_th_v
        self.eps = eps
        self.center_h = center_h
        self.extractor = HeadExtractor(self.model)
        self.U: Optional[torch.Tensor] = None  # (K,ku)
        self.V: Optional[torch.Tensor] = None  # (d,kv)
        self.h_mu: Optional[torch.Tensor] = None

    @staticmethod
    def _top_eigvecs_from_cov(cov: torch.Tensor, eps_th: float) -> torch.Tensor:
        # cov: (D,D) symmetric
        evals, evecs = torch.linalg.eigh(cov)
        # sort descending
        idx = torch.argsort(evals, descending=True)
        evals = evals[idx]
        evecs = evecs[:, idx]
        energy = evals.clamp_min(0)
        cum = torch.cumsum(energy, dim=0) / energy.sum().clamp_min(1e-12)
        k = int(torch.searchsorted(cum, torch.tensor(eps_th, device=cum.device)).item() + 1)
        k = max(1, min(k, evecs.size(1)))
        return evecs[:, :k]

    def fit(self, loader: Iterable[Batch]):
        device = next(self.model.parameters()).device
        deltas: List[torch.Tensor] = []
        hs: List[torch.Tensor] = []
        with torch.no_grad():
            for x, _ in _iter_inputs(loader):
                x = _to_device(x, device)
                head_io = self.extractor.forward(x)
                hs.append(head_io.h.detach())
        H = torch.cat(hs, dim=0)
        self.h_mu = H.mean(dim=0, keepdim=True) if self.center_h else torch.zeros(1, H.size(1), device=device)

        # Now compute deltas (requires grad) and gather centered hs for covariance
        deltas = []
        hs_c = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            logits = head_io.logits.detach().requires_grad_(True)
            h = head_io.h
            if self.center_h:
                h = h - self.h_mu
            loss = _loss_from_logits(logits, loss_type=self.loss_type, temperature=self.temperature)
            delta = torch.autograd.grad(loss.sum(), logits, retain_graph=False, create_graph=False)[0]
            deltas.append(delta.detach())
            hs_c.append(h.detach())

        D = torch.cat(deltas, dim=0)  # (N,K)
        Hc = torch.cat(hs_c, dim=0)   # (N,d)

        # Covariances
        Dm = D - D.mean(dim=0, keepdim=True)
        Hm = Hc - Hc.mean(dim=0, keepdim=True)
        cov_u = (Dm.T @ Dm) / max(1, Dm.size(0) - 1)
        cov_v = (Hm.T @ Hm) / max(1, Hm.size(0) - 1)
        cov_u = cov_u + 1e-6 * torch.eye(cov_u.size(0), device=cov_u.device)
        cov_v = cov_v + 1e-6 * torch.eye(cov_v.size(0), device=cov_v.device)

        self.U = self._top_eigvecs_from_cov(cov_u, self.eps_th_u).detach()
        self.V = self._top_eigvecs_from_cov(cov_v, self.eps_th_v).detach()

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if self.U is None or self.V is None or self.h_mu is None:
            raise RuntimeError("TwoSidedHeadGradResidual.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        U = self.U.to(device)
        V = self.V.to(device)
        h_mu = self.h_mu.to(device)
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            logits = head_io.logits.detach().requires_grad_(True)
            h = head_io.h
            if self.center_h:
                h = h - h_mu
            loss = _loss_from_logits(logits, loss_type=self.loss_type, temperature=self.temperature)
            delta = torch.autograd.grad(loss.sum(), logits, retain_graph=False, create_graph=False)[0]

            # Compute residual without materializing G when possible
            # G = delta ⊗ h
            # Normalize by Frobenius: ||G||_F = ||delta|| * ||h||
            nd = torch.linalg.vector_norm(delta, ord=2, dim=1).clamp_min(self.eps)
            nh = torch.linalg.vector_norm(h, ord=2, dim=1).clamp_min(self.eps)
            # normalized factors
            d_hat = delta / nd.unsqueeze(1)
            h_hat = h / nh.unsqueeze(1)

            # Project factors
            d_proj = (d_hat @ U) @ U.T
            h_proj = (h_hat @ V) @ V.T
            # Residual of outer product under two-sided projection:
            # ||d_hat h_hat^T - d_proj h_proj^T||_F
            # compute using ||A||^2 = ||a||^2||b||^2 for outer products + cross term
            # Let A = a b^T, B = c d^T
            # ||A-B||_F^2 = ||a||^2||b||^2 + ||c||^2||d||^2 - 2 (a^T c)(b^T d)
            a = d_hat
            b = h_hat
            c = d_proj
            d = h_proj
            a2 = (a * a).sum(dim=1)
            b2 = (b * b).sum(dim=1)
            c2 = (c * c).sum(dim=1)
            d2 = (d * d).sum(dim=1)
            ac = (a * c).sum(dim=1)
            bd = (b * d).sum(dim=1)
            r2 = a2 * b2 + c2 * d2 - 2.0 * ac * bd
            r = torch.sqrt(r2.clamp_min(0.0))
            scores.append(r.detach().cpu())
        return torch.cat(scores, dim=0)


class TwoSidedHeadGradCodeMahalanobis(OODMethod):
    """PROPOSED: vectorize the two-sided code A=U^T G_hat V and fit class-conditional Gaussians."""

    def __init__(
        self,
        model: torch.nn.Module,
        loss_type: str = "uniform_kl",
        temperature: float = 1.0,
        eps_th_u: float = 0.95,
        eps_th_v: float = 0.95,
        shrinkage: float = 1e-6,
        center_h: bool = True,
        include_residual: bool = True,
        include_log_mag: bool = True,
        eps: float = 1e-12,
    ):
        super().__init__(model)
        self.loss_type = loss_type
        self.temperature = temperature
        self.eps_th_u = eps_th_u
        self.eps_th_v = eps_th_v
        self.shrinkage = shrinkage
        self.center_h = center_h
        self.include_residual = include_residual
        self.include_log_mag = include_log_mag
        self.eps = eps
        self.extractor = HeadExtractor(self.model)
        self.U: Optional[torch.Tensor] = None
        self.V: Optional[torch.Tensor] = None
        self.h_mu: Optional[torch.Tensor] = None
        self.class_stats: Dict[int, Tuple[np.ndarray, np.ndarray]] = {}

    def _embed(self, delta: torch.Tensor, h: torch.Tensor) -> torch.Tensor:
        """Return embedding per sample as torch tensor on current device."""
        assert self.U is not None and self.V is not None
        U = self.U
        V = self.V
        # magnitudes
        nd = torch.linalg.vector_norm(delta, ord=2, dim=1).clamp_min(self.eps)
        nh = torch.linalg.vector_norm(h, ord=2, dim=1).clamp_min(self.eps)
        d_hat = delta / nd.unsqueeze(1)
        h_hat = h / nh.unsqueeze(1)

        # two-sided code for normalized G_hat = d_hat ⊗ h_hat
        du = d_hat @ U  # (B,ku)
        hv = h_hat @ V  # (B,kv)
        # A = (du) ⊗ (hv) as ku x kv; vectorize
        # vec(A) can be computed via outer product per sample
        A = torch.einsum("bi,bj->bij", du, hv)  # (B,ku,kv)
        feat_list = [A.flatten(1)]

        if self.include_residual:
            d_proj = (d_hat @ U) @ U.T
            h_proj = (h_hat @ V) @ V.T
            a = d_hat
            b = h_hat
            c = d_proj
            d = h_proj
            a2 = (a * a).sum(dim=1)
            b2 = (b * b).sum(dim=1)
            c2 = (c * c).sum(dim=1)
            d2 = (d * d).sum(dim=1)
            ac = (a * c).sum(dim=1)
            bd = (b * d).sum(dim=1)
            r2 = a2 * b2 + c2 * d2 - 2.0 * ac * bd
            r = torch.sqrt(r2.clamp_min(0.0)).unsqueeze(1)
            feat_list.append(r)

        if self.include_log_mag:
            logmag = (torch.log(nd) + torch.log(nh)).unsqueeze(1)
            feat_list.append(logmag)

        return torch.cat(feat_list, dim=1)

    def fit(self, loader: Iterable[Batch]):
        # First learn U,V using the residual method's fit procedure
        tmp = TwoSidedHeadGradResidual(
            self.model,
            loss_type=self.loss_type,
            temperature=self.temperature,
            eps_th_u=self.eps_th_u,
            eps_th_v=self.eps_th_v,
            center_h=self.center_h,
        )
        tmp.fit(loader)
        self.U = tmp.U
        self.V = tmp.V
        self.h_mu = tmp.h_mu

        device = next(self.model.parameters()).device
        U = self.U.to(device)
        V = self.V.to(device)
        h_mu = self.h_mu.to(device)
        self.U, self.V, self.h_mu = U.detach(), V.detach(), h_mu.detach()

        # Now collect embeddings and fit class-conditional Gaussians
        embs: List[np.ndarray] = []
        labels: List[int] = []
        for x, y in _iter_inputs(loader):
            if y is None:
                raise RuntimeError("TwoSidedHeadGradCodeMahalanobis.fit requires labels.")
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            logits = head_io.logits.detach().requires_grad_(True)
            h = head_io.h
            if self.center_h:
                h = h - self.h_mu
            loss = _loss_from_logits(logits, loss_type=self.loss_type, temperature=self.temperature)
            delta = torch.autograd.grad(loss.sum(), logits, retain_graph=False, create_graph=False)[0]
            z = self._embed(delta, h).detach().cpu().numpy()
            embs.append(z)
            labels.extend(y.detach().cpu().reshape(-1).tolist())
        Z = np.concatenate(embs, axis=0)
        y = np.array(labels)

        self.class_stats = {}
        for c in np.unique(y):
            Zc = Z[y == c]
            mu = Zc.mean(axis=0)
            cov = np.cov(Zc, rowvar=False) + self.shrinkage * np.eye(Zc.shape[1])
            self.class_stats[int(c)] = (mu, np.linalg.inv(cov))

    def compute_ood_scores(self, loader: Iterable[Batch]) -> torch.Tensor:
        if self.U is None or self.V is None or self.h_mu is None or not self.class_stats:
            raise RuntimeError("TwoSidedHeadGradCodeMahalanobis.fit must be called before scoring.")
        device = next(self.model.parameters()).device
        scores: List[torch.Tensor] = []
        for x, _ in _iter_inputs(loader):
            x = _to_device(x, device)
            head_io = self.extractor.forward(x)
            logits = head_io.logits.detach().requires_grad_(True)
            h = head_io.h
            if self.center_h:
                h = h - self.h_mu
            loss = _loss_from_logits(logits, loss_type=self.loss_type, temperature=self.temperature)
            delta = torch.autograd.grad(loss.sum(), logits, retain_graph=False, create_graph=False)[0]
            Z = self._embed(delta, h).detach().cpu().numpy()
            batch_scores = []
            for i in range(Z.shape[0]):
                zi = Z[i]
                best = np.inf
                for mu, inv_cov in self.class_stats.values():
                    d = zi - mu
                    md = float(np.sqrt(d.T @ inv_cov @ d))
                    best = min(best, md)
                batch_scores.append(best)
            scores.append(torch.tensor(batch_scores))
        return torch.cat(scores, dim=0)


# ----------------------------
# Convenience registry
# ----------------------------

def build_method_registry(model: torch.nn.Module) -> Dict[str, OODMethod]:
    """Return a dict of name -> instantiated method with default hyperparameters."""
    return {
        "msp": MSP(model),
        "energy": EnergyBased(model),
        "odin": Odin(model),
        "feat_knn": FeatureKNN(model, k=10),
        "feat_maha": FeatureMahalanobis(model),
        "gradnorm": GradNorm(model, loss_type="uniform_kl", p="fro"),
        "gradorth": GradOrth(model, eps_th=0.95, loss_type="uniform_kl"),
        "lowdim_grad_resid": LowDimGradResidual(model, loss_type="uniform_kl", n_components=0.95),
        "gradvec_maha": GradVecMahalanobis(model, loss_type="uniform_kl", n_components=0.95),
        "twosided_resid": TwoSidedHeadGradResidual(model, loss_type="uniform_kl", eps_th_u=0.95, eps_th_v=0.95),
        "twosided_code_maha": TwoSidedHeadGradCodeMahalanobis(model, loss_type="uniform_kl", eps_th_u=0.95, eps_th_v=0.95),
    }


if __name__ == "__main__":
    # Minimal smoke test with a toy model
    class SimpleModel(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.fc1 = torch.nn.Linear(10, 20)
            self.fc2 = torch.nn.Linear(20, 10)
            self.fc3 = torch.nn.Linear(10, 5)

        def forward(self, x):
            x = torch.relu(self.fc1(x))
            x = torch.relu(self.fc2(x))
            return self.fc3(x)

    torch.manual_seed(0)
    model = SimpleModel()

    # Create a fake ID loader
    id_samples = [(torch.randn(8, 10), torch.randint(0, 5, (8,))) for _ in range(10)]
    ood_samples = [(torch.randn(8, 10) + 2.0, torch.randint(0, 5, (8,))) for _ in range(5)]

    methods = build_method_registry(model)

    # Fit those that need fitting
    for name, m in methods.items():
        try:
            m.fit(id_samples)
        except Exception:
            pass

    # Score
    for name, m in methods.items():
        try:
            s_id = m.compute_ood_scores(id_samples)
            s_ood = m.compute_ood_scores(ood_samples)
            print(f"{name:20s} | id_mean={s_id.mean():.3f} ood_mean={s_ood.mean():.3f}")
        except Exception as e:
            print(f"{name:20s} | skipped ({e})")
